export enum APIMemberKind {
  CallSignature = "CallSignature",
  Class = "Class",
  ConstructSignature = "ConstructSignature",
  Constructor = "Constructor",
  EntryPoint = "EntryPoint",
  Enum = "Enum",
  EnumMember = "EnumMember",
  Function = "Function",
  IndexSignature = "IndexSignature",
  Interface = "Interface",
  Method = "Method",
  MethodSignature = "MethodSignature",
  Model = "Model",
  Namespace = "Namespace",
  None = "None",
  Package = "Package",
  Property = "Property",
  PropertySignature = "PropertySignature",
  TypeAlias = "TypeAlias",
  Variable = "Variable",
}
