// biome-ignore-all lint/style/useNamingConvention: Some languages use all uppercase letters for their names.

/** Represents a map of levels of headings for headers with their respective literal content. */
export type HeadingLevelsMap<Content extends string> = {
	[HeadingLevel.One]: `# ${Content}`;
	[HeadingLevel.Three]: `### ${Content}`;
	[HeadingLevel.Two]: `## ${Content}`;
};

/**
 * Represents a type that is a recursive array.
 *
 * @typeParam Item - The shape of the item in the array.
 */
export type RecursiveArray<Item> = readonly (Item | RecursiveArray<Item>)[];

/** Represents the suported languages for Discord code blocks. */
export enum CodeBlockLanguage {
	ABNF = "abnf",
	ANSI = "ansi",
	ARMAssembler = "armasm",
	AVRAssembler = "avrasm",
	AccessLogs = "accesslog",
	ActionScript = "actionscript",
	Ada = "ada",
	Apache = "apache",
	AppleScript = "applescript",
	Arcade = "arcade",
	Arduino = "arduino",
	AsciiDoc = "asciidoc",
	AspectJ = "aspectj",
	AutoHotkey = "autohotkey",
	AutoIt = "autoit",
	Awk = "awk",
	BNF = "bnf",
	Bash = "bash",
	Batch = "bat",
	Brainfuck = "brainfuck",
	C = "c",
	CAL = "cal",
	CMake = "cmake",
	COS = "cos",
	CPlusPlus = "c++",
	CSS = "css",
	CSharp = "c#",
	CapnProto = "capnproto",
	Clojure = "clojure",
	CoffeeScript = "coffeescript",
	Coq = "coq",
	Crmsh = "crmsh",
	Crystal = "crystal",
	D = "d",
	DNS = "dns",
	DOS = "dos",
	DTS = "dts",
	Dart = "dart",
	Delphi = "delphi",
	Diff = "diff",
	Dockerfile = "dockerfile",
	Dsconfig = "dsconfig",
	Dust = "dust",
	EBNF = "ebnf",
	Elixir = "elixir",
	Elm = "elm",
	Erlang = "erlang",
	Excel = "excel",
	FSharp = "f#",
	Fix = "fix",
	Fortran = "fortran",
	GAUSS = "gauss",
	GCode = "gcode",
	Gams = "gams",
	Gherkin = "gherkin",
	Go = "go",
	Golo = "golo",
	Gradle = "gradle",
	GraphQL = "graphql",
	Groovy = "groovy",
	HTML = "html",
	Haml = "haml",
	Handlebars = "handlebars",
	Haskell = "haskell",
	Haxe = "haxe",
	Hy = "hy",
	INI = "ini",
	IRPF90 = "irpf90",
	Inform7 = "inform7",
	JSON = "json",
	JSX = "jsx",
	Java = "java",
	JavaScript = "javascript",
	Julia = "julia",
	JuliaREPL = "julia-repl",
	Kotlin = "kotlin",
	LDIF = "ldif",
	LaTeX = "text",
	Lasso = "lasso",
	Less = "less",
	Lisp = "lisp",
	LiveCodeServer = "livecodeserver",
	LiveScript = "livescript",
	Lua = "lua",
	MEL = "mel",
	MIPSAssembler = "mips",
	Makefile = "makefile",
	Mathematica = "mathematica",
	Matlab = "matlab",
	Markdown = "markdown",
	Maxima = "maxima",
	Mercury = "mercury",
	Mizar = "mizar",
	Monkey = "monkey",
	MoonScript = "moonscript",
	N1QL = "n1ql",
	NSIS = "nsis",
	Nginx = "nginx",
	Nim = "nim",
	Nix = "nix",
	OCaml = "ocaml",
	ObjectiveC = "objectivec",
	OneC = "1c",
	OpenGLShardingLanguage = "glsl",
	OpenSCAD = "openscad",
	Oxygene = "oxygene",
	PF = "pf",
	PHP = "php",
	Parser3 = "parser3",
	Perl = "perl",
	Plaintext = "plaintext",
	Pony = "pony",
	PostgreSQL = "pqsql",
	PowerShell = "powershell",
	Processing = "processing",
	Profile = "profile",
	Prolog = "prolog",
	Properties = "properties",
	ProtocolBuffers = "proto",
	Puppet = "puppet",
	Python = "python",
	PythonREPL = "python-repl",
	Q = "q",
	QML = "qml",
	R = "r",
	ReasonML = "reasonml",
	RenderManRIB = "rib",
	RenderManRSL = "rsl",
	Roboconf = "roboconf",
	Ruby = "ruby",
	RulesLanguage = "ruleslanguage",
	Rust = "rust",
	SAS = "sas",
	SCSS = "scss",
	SML = "sml",
	SQL = "sql",
	STEPPart21 = "p21",
	Scala = "scala",
	Scheme = "scheme",
	Scilab = "scilab",
	Shell = "shell",
	Smali = "smali",
	Smalltalk = "smalltalk",
	Stan = "stan",
	Stata = "stata",
	Stylus = "stylus",
	Swift = "swift",
	TAP = "tap",
	TCL = "tcl",
	TOML = "toml",
	TSX = "tsx",
	Thrift = "thrift",
	Twig = "twig",
	TypeScript = "typescript",
	VBNet = "vbnet",
	VBScript = "vbsript",
	VHDL = "vhdl",
	Vala = "vala",
	Verilog = "verilog",
	VimScript = "vim",
	X86Assembly = "x86asm",
	XL = "xl",
	XPlusPlus = "x++",
	XQuery = "xquery",
	YAML = "yaml",
	Zephir = "zephir",
}

/** Represents the faces from the Discord chat input command. */
export enum Faces {
	Shrug = "¯\\_(ツ)_/¯",
	Tableflip = "(╯°□°)╯︵ ┻━┻",
	Unflip = "┬─┬ノ( º _ ºノ)",
}

/**
 * Represents the navigation types for a guild.
 *
 * @see https://discord.com/developers/docs/reference#message-formatting-guild-navigation-types
 */
export enum GuildNavegationType {
	Browse = "<id:browse>",
	Customize = "<id:customize>",
	Guide = "<id:guide>",
	LinkedRoles = "<id:linked-roles>",
}

/** Represents the levels of headings for headers. */
export enum HeadingLevel {
	One = 1,
	Three = 3,
	Two = 2,
}

/**
 * Represents the styles for timestamps.
 *
 * @see https://discord.com/developers/docs/reference#message-formatting-timestamp-styles
 */
export enum TimestampStyle {
	FullDateShortTime = "F",
	LongDate = "D",
	LongDateShortTime = "f",
	MediumTime = "T",
	Relative = "R",
	ShortDate = "d",
	ShortDateMediumTime = "S",
	ShortDateShortTime = "s",
	ShortTime = "t",
}
