/**
 * The available languages for application command localizations.
 * @see https://discord.com/developers/docs/reference#locales
 */
export enum Locales {
	Bulgarian = "bg",
	ChineseCN = "zh-CN",
	ChineseTW = "zh-TW",
	Croatian = "hr",
	Czech = "cs",
	Danish = "da",
	Dutch = "nl",
	EnglishUK = "en-GB",
	EnglishUS = "en-US",
	Finnish = "fi",
	French = "fr",
	German = "de",
	Greek = "el",
	Hindi = "hi",
	Hungarian = "hu",
	Indonesian = "id",
	Italian = "it",
	Japanese = "ja",
	Korean = "ko",
	Lithuanian = "lt",
	Norwegian = "no",
	Polish = "pl",
	PortugueseBR = "pt-BR",
	Romanian = "ro",
	Russian = "ru",
	SpanishES = "es-ES",
	SpanishLATAM = "es-419",
	Swedish = "sv-SE",
	Thai = "th",
	Turkish = "tr",
	Ukrainian = "uk",
	Vietnamese = "vi",
}
