name: 🌀 Continuous Integration

on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: 📂 Checkout Code
              uses: actions/checkout@v5

            - name: 🔧 Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: 📦 Install PNPM
              run: npm install -g pnpm

            - name: 📥 Install Dependencies
              run: pnpm install

            - name: 🦺 Build Packages
              run: pnpm build

            - name: 🧪 Run Vitest
              run: pnpm vitest
